### PR TITLE
Add arch linux package

### PR DESCRIPTION
**Pull request by Drarig29**
Hi! A friend of mine shared me your tweet! That's a very nice tool!

I just released an AUR package which relies on the [.tar.gz](https://github.com/ArthurSonzogni/json-tui/releases/download/v1.0.3/json-tui-1.0.3-Linux.tar.gz) in your Release page.

Cheers!

### CODE REVIEW

**Comment by ArthurSonzogni** [comment]
Wow, Arch linux users are the best!
I just released/tweeted 2760 seconds ago and there is already an Arch Linux package ;-)

I hope someone would come like previously with [rgb-tui](https://github.com/ArthurSonzogni/rgb-tui) and [git-tui](https://github.com/ArthurSonzogni/git-tui). Thank you!

**Comment by ArthurSonzogni** [comment]
This LGTM! I have read:
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=json-tui-bin
and this is indeed looking good!

To support more architecture, I am wondering if this wouldn't be better to also support building using cmake like we did previously:
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=rgb-tui-git

Anyway, if someone needs it, we can do it later. This patch is a clear improvement.

**Comment by ArthurSonzogni** [comment]
Hi @Drarig29 

I fixed major bugs recently (parsing float and big numbers), performance issue.
I would like to update the package to v1.1.0 with this patch:
```patch
From 57111b7b5f122cdb55ecb56d32e2312ddbc6cfdd Mon Sep 17 00:00:00 2001
From: ArthurSonzogni <sonzogniarthur@gmail.com>
Date: Mon, 10 Jan 2022 21:06:57 +0100
Subject: [PATCH] Add v1.1.0

---
 PKGBUILD | 4 ++--
 1 file changed, 2 insertions(+), 2 deletions(-)

diff --git a/PKGBUILD b/PKGBUILD
index b43f6f8..a3e8506 100644
--- a/PKGBUILD
+++ b/PKGBUILD
@@ -1,7 +1,7 @@
 # Maintainer: drarig29 <corentingirard.dev@gmail.com>
 
 pkgname=json-tui-bin
-pkgver=1.0.3
+pkgver=1.1.0
 pkgrel=1
 pkgdesc="A JSON terminal UI made in C++"
 arch=("x86_64")
@@ -10,7 +10,7 @@ license=("MIT")
 provides=("json-tui")
 conflicts=("json-tui")
 source=("https://github.com/ArthurSonzogni/json-tui/releases/download/v${pkgver}/json-tui-${pkgver}-Linux.tar.gz")
-sha256sums=('6d8eacf5d23539d8bbe7b890f26ff58aafdba0ce0e06d5252dff642faf32a6ad')
+sha256sums=('623254ee6e9f974ba7337c365926accd6f32b939bcccb7510396f9a02924a4ac')
 
 package() {
   install -Dm755 json-tui-${pkgver}-Linux/bin/json-tui -t "$pkgdir/usr/bin"
-- 
2.30.2

```

I guess I might need to do it several time. Would it be possible to become the co-maintainer of this package?

My AUR username is "arthursonzogni".
My AUR email is sonzogniarthur at gmail
For now, I get:
```bash
git-receive-pack: permission denied: arthursonzogni
```

**Comment by Drarig29** [comment]
Done ☺

Maybe you could add keywords too.

**Comment by Drarig29** [comment]
By the way, you need to update the `.SRCINFO` file too.

To generate it:

```shell
makepkg --printsrcinfo > .SRCINFO
```

**Pull request merged**
